name = "fcm-web-push-worker-dev"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
queue = "scheduled-notifications-dev"
binding = "SCHEDULED_NOTIFICATIONS_QUEUE"

[[queues.consumers]]
queue = "scheduled-notifications-dev"
max_batch_size = 10 